replicaCount: 1
image:
  repository: expenseflow-expense
  tag: local
service:
  type: ClusterIP
  port: 5000

containerPort: 5000
serviceAccount:
  create: false
  name: ""
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
